"""
Autonomous AI Vacuum Robot - Vision & Object Detection Pipeline
Perception system running on Raspberry Pi 4 for real-time obstacle avoidance,
room feature detection, and cleaning navigation benchmarks.
"""

import time
import cv2
from ultralytics import YOLO
from picamera2 import Picamera2

# 1. Initialize Camera (Keep native 640x480 resolution)
picam2 = Picamera2()
config = picam2.create_preview_configuration(main={"format": "RGB888", "size": (640, 480)})
picam2.configure(config)
picam2.start()
time.sleep(1.0)

# Capture raw 4:3 frame
frame = picam2.capture_array()

# 2. Load the NCNN-optimized model directory directly through Ultralytics
# Point to the folder generated by the export step
model = YOLO("yolov8n_ncnn_model")

# Warmup run
_ = model(frame, imgsz=320, verbose=False)

# 3. Inference Run
# Pass raw frame and set imgsz=320 (Ultralytics handles aspect-ratio preserving letterbox)
start_time = time.time()
results = model(frame, imgsz=320, verbose=False)
latency = time.time() - start_time

result = results[0]
print(f"Latency: {latency:.4f}s ({1/latency:.2f} FPS)")
print(f"Speed breakdown (ms): {result.speed}")
print(f"Detections: {len(result.boxes)}")

# Extract detected objects and their class names
detections = []
for box in result.boxes:
    class_id = int(box.cls[0].item())
    class_name = result.names[class_id]
    confidence = float(box.conf[0].item())
    xyxy = box.xyxy[0].tolist()  # [x_min, y_min, x_max, y_max]

    detections.append({
        "name": class_name,
        "confidence": round(confidence, 2),
        "box": [round(coord, 1) for coord in xyxy]
    })

    print(f"Detected: {class_name:<15} | Conf: {confidence:.2%} | Box: {xyxy}")

print(f"\nTotal detections: {len(detections)}")

picam2.stop()